# Generated by Django 3.1.1 on 2020-10-01 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='task title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('created', models.DateField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('completed', models.DateField(db_index=True, null=True, verbose_name='planed completed date')),
                ('status', models.CharField(choices=[('new', 'New'), ('planned', 'Planned'), ('work', 'Work'), ('completed', 'Completed')], default='new', max_length=10, verbose_name='роль пользователя')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField(max_length=1000, verbose_name='change data')),
                ('old_value', models.TextField(max_length=1000, verbose_name='change data')),
                ('new_value', models.TextField(max_length=1000, verbose_name='change data')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date of change')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api.task', verbose_name='task id')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
