# Generated by Django 3.1.2 on 2020-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('planned', 'Planned'), ('work', 'Work'), ('completed', 'Completed')], default='new', max_length=10, verbose_name='task status'),
        ),
    ]
