# Generated by Django 3.1.1 on 2020-10-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201002_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='old_value',
            field=models.TextField(max_length=1000, null=True, verbose_name='change data'),
        ),
    ]
